export const FETCH_BOOKS = 'FETCH_BOOKS';
export const BOOK_SELECTED = 'BOOK_SELECTED';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';